unique_ids:
  forms:
    LotsBrocante: POE4REJ5QAKKYRLMAGJJIBVZHATN667J
  modules: {}
  server_modules: {}
  assets:
    Brocante.jpg: '1722700733679205563233760.93744'
    standard-page.html: NSFMPCZYQNHUF7PBFAJX6OAJ6JYZLKHM
    theme.css: 2CRSD2FXBMKDILPQEMMZSZCE2ZSKQQ2Y
  scripts: {}
